sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

install:
  - alias make="make -j" && ./thrift/build/deps_ubuntu_14.04.sh

script:
  - alias make="make -j" && ./thrift/build/travis/install.sh

notifications:
  email:
    recipients:
      - thrift_oncall@fb.com
    on_success: never
    on_failure: always
